### find all aliases
GET http://localhost:3000/alias

### find all aliases that are mapped
GET http://localhost:3000/alias?mappedOnly=true

### map an alias to a product when the alias does not exists
PUT http://localhost:3000/alias/-12?productId=1

### map an alias to a product that does not exist
PUT http://localhost:3000/alias/4?productId=12358

### map an alias to a product
PUT http://localhost:3000/alias/4?productId=15

### search for a product with an alias that exists and is not mapped
POST http://localhost:3000/alias/search
Content-Type: application/json

{
  "name": "Tasty Steel Pizza",
  "seller": "Hammes, Morar and Cremin"
}

### search for a product with an alias that exists and is mapped
POST http://localhost:3000/alias/search
Content-Type: application/json

{
  "name": "Elegant Frozen Tuna",
  "seller": "Bahringer LLC"
}

### search for a product with an alias that does not exists
POST http://localhost:3000/alias/search
Content-Type: application/json

{
  "name": "Samsung Tv",
  "seller": "Musimundo"
}