### find all aliases
GET http://localhost:3000/alias

### find all aliases that are mapped
GET http://localhost:3000/alias?mappedOnly=true

### map an alias to a product when the alias does not exists
PUT http://localhost:3000/alias/-12?productId=1

### map an alias to a product
PUT http://localhost:3000/alias/1?productId=1

### search for a product with an alias that is not mapped
POST http://localhost:3000/alias/search
Content-Type: application/json

{
  "name": "Fantastic Rubber Shoes",
  "seller": "Welch Group"
}

### search for a product with an alias that exists and is mapped
POST http://localhost:3000/alias/search
Content-Type: application/json

{
  "name": "Rustic Fresh Ball",
  "seller": "Greenholt, Nader and Wilderman"
}

### search for a product with an alias that does not exists
POST http://localhost:3000/alias/search
Content-Type: application/json

{
  "name": "Samsung Tv",
  "seller": "Musimundo"
}

### find all categories
GET http://localhost:3000/categories

### create a new parent category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Electronics"
}

### create a new category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Displays",
  "parentCategory": "Electronics"
}

### delete a category
DELETE http://localhost:3000/categories/Displays

### update a category
PUT http://localhost:3000/categories/Intelligent
Content-Type: application/json

{
  "parentCategory": "Electronics"
}

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/search

###
GET http://localhost:3000/products/1

###
DELETE http://localhost:3000/products/1

###
GET http://localhost:3000/tags

###
POST http://localhost:3000/products
Content-Type: application/json

{}

###
PUT http://localhost:3000/products/1
Content-Type: application/json

{}
