###
GET http://localhost:3000/alias

###
GET http://localhost:3000/alias/search

###
PUT http://localhost:3000/alias/SamsungTv

###
GET http://localhost:3000/categories

###
DELETE http://localhost:3000/categories/Electronics

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/search

###
GET http://localhost:3000/products/1

###
DELETE http://localhost:3000/products/1

###
GET http://localhost:3000/tags

###
POST http://localhost:3000/categories
Content-Type: application/json

{}

###
PUT http://localhost:3000/categories/Electronics
Content-Type: application/json

{}

###
POST http://localhost:3000/products
Content-Type: application/json

{}

###
PUT http://localhost:3000/products/1
Content-Type: application/json

{}
