### find all categories
GET http://localhost:3000/categories

### create a new parent category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Electronics"
}

### create a new category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Displays",
  "parentCategory": "Electronics"
}

### delete a category
DELETE http://localhost:3000/categories/Displays

### update a category
PUT http://localhost:3000/categories/Steel

Content-Type: application/json

{
  "parentCategory": "Electronics"
}