### find all products
GET http://localhost:3000/products

### find a specific product that does not exist
GET http://localhost:3000/products/-1

### find a specific product
GET http://localhost:3000/products/10

### delete a speciifc product
DELETE http://localhost:3000/products/10

###
POST http://localhost:3000/products
Content-Type: application/json

{}

###
PUT http://localhost:3000/products/1
Content-Type: application/json

{}

###
GET http://localhost:3000/products/search

###
GET http://localhost:3000/tags
